# Basics

In [4]:
from quimb import *

## Representations

In [5]:
data = [1, 2j, -3]

In [10]:
qu(data, qtype='ket')

[[ 1.+0.j]
 [ 0.+2.j]
 [-3.+0.j]]

In [11]:
qu(data, qtype='ket', normalized=True)

[[ 0.267261+0.j      ]
 [ 0.      +0.534522j]
 [-0.801784+0.j      ]]

In [12]:
qu(data, qtype='bra')

[[ 1.-0.j  0.-2.j -3.-0.j]]

In [13]:
qu(data, qtype='dop')

[[ 1.+0.j  0.-2.j -3.+0.j]
 [ 0.+2.j  4.+0.j  0.-6.j]
 [-3.+0.j  0.+6.j  9.+0.j]]

In [15]:
qu(data, qtype='dop', sparse=True)

<3x3 sparse matrix of type '<class 'numpy.complex128'>'
	with 9 stored elements in Compressed Sparse Row format>

In [16]:
ket(data)

[[ 1.+0.j]
 [ 0.+2.j]
 [-3.+0.j]]

In [17]:
bra(data)

[[ 1.-0.j  0.-2.j -3.-0.j]]

In [21]:
dop(data)

[[ 1.+0.j  0.-2.j -3.+0.j]
 [ 0.+2.j  4.+0.j  0.-6.j]
 [-3.+0.j  0.+6.j  9.+0.j]]

In [22]:
sparse(data)

<3x1 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

## Operations

In [25]:
psi = 1.0j * bell_state('psi-')
psi

[[ 0.+0.j      ]
 [ 0.+0.707107j]
 [-0.-0.707107j]
 [ 0.+0.j      ]]

In [26]:
psi.H

[[ 0.-0.j        0.-0.707107j -0.+0.707107j  0.-0.j      ]]

In [27]:
psi = up()
psi

[[1.+0.j]
 [0.+0.j]]

In [29]:
psi.H @ psi

[[1.+0.j]]

In [32]:
X = pauli('X')
X

[[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]

In [33]:
X @ psi

[[0.+0.j]
 [1.+0.j]]

In [34]:
psi.H @ X @ psi

[[0.+0.j]]

In [35]:
expec(psi, psi)

1.0

In [36]:
expec(psi, X)

0j

In [37]:
psi = rand_ket(2**20)

In [38]:
A = rand_herm(2**20, sparse=True) + speye(2**20)

In [39]:
A

<1048576x1048576 sparse matrix of type '<class 'numpy.complex128'>'
	with 11534268 stored elements in Compressed Sparse Row format>

In [40]:
expec(A, psi)

1.000339882310866

In [41]:
%%timeit
expec(A, psi)

80 ms ± 1.72 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Tensoring

In [48]:
dims = [2] * 10

In [57]:
X = pauli('X')
X

[[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]

In [51]:
IIIXXIIIII = ikron(X, dims, inds=[3, 4])

In [53]:
IIIXXIIIII.shape

(1024, 1024)

In [58]:
dims = [2] * 3
XZ = pauli('X') & pauli('Z')

In [59]:
XZ

[[ 0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j -0.+0.j  0.+0.j -1.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j  0.+0.j -0.+0.j]]

In [61]:
ZIX = pkron(XZ, dims, inds=[2, 0])

In [65]:
ZIX

[[ 0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j -0.+0.j -1.+0.j -0.+0.j -0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j -1.+0.j -0.+0.j -0.+0.j -0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j -0.+0.j -0.+0.j -0.+0.j -1.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j -0.+0.j -0.+0.j -1.+0.j -0.+0.j]]

In [63]:
ZIX.real.astype(int)

[[ 0  1  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0 -1  0]]

## Partial Trace

Start with random system of 10 qubits, and we want just the reduced density matrix describing the first and last spins.

In [66]:
dims = [2] * 10
D = prod(dims)

In [69]:
psi = rand_ket(D)

In [71]:
psi

[[-0.010666+0.009691j]
 [-0.039857-0.023547j]
 [ 0.015557-0.016029j]
 ...
 [ 0.014669-0.023148j]
 [ 0.009883-0.033724j]
 [-0.006898+0.003787j]]

In [72]:
rho_ab = ptr(psi, dims, [0, 9])

In [76]:
rho_ab.round(3)

[[ 0.23 +0.j     0.01 -0.003j  0.   -0.029j  0.005-0.002j]
 [ 0.01 +0.003j  0.265+0.j    -0.008+0.017j  0.011-0.006j]
 [ 0.   +0.029j -0.008-0.017j  0.271+0.j    -0.012+0.005j]
 [ 0.005+0.002j  0.011+0.006j -0.012-0.005j  0.234+0.j   ]]